### ISSUE TITLE
Singnificant increase in tx mining from ~1 minute up to ~ 180 - 360 minutes (3 - 6 hours) over last 5 days

### ISSUE THREAD

**Issue by Gelassen** [eth-clients/goerli#127] opened 2022-10-21 08:44 UTC
Hello Dev Team, 
I just noticed the significant increase in tx mining from ~1 minute up to ~ 180 - 360 minutes (3 - 6 hours) over last 5 days. Does any recent changes from you side cause it? 

Yesterday I faced with issue my working code start throw timeout exception: 

`Transaction receipt was not generated after 600 seconds for transaction: 0xb92c3df992ea0ad240ae0e1ed46da932d0db2725759137b417524e9c86d69677`

I had been debugging the code for a bug, but today morning I found the tx appears on etherscan after 3-6 hours when it had been mined. https://goerli.etherscan.io/address/0x3106248FBB449ED92b03d6f93F43f464CD95b74d. 
10-6 days ago it took near a minute to get tx receipt and found out the tx on etherscan. 

Possibly linked to this issue: https://github.com/eth-clients/goerli/issues/126

**Comment by q9f** [comment] 2022-10-25 10:46
duplicate of #126

**Closed by q9f** 2022-10-25 10:46 UTC

**Comment by Gelassen** [comment] 2022-10-25 10:54
@q9f, would you assign #126 on yourself to start work on it? Could you please share a context behind this issue (what had caused it?) and estimate on time the issue would be solved&released?

**Comment by q9f** [comment] 2022-10-25 16:57
This repository is used to coordinate the testnet configurations and initiatives, not to resolve issues with infrastructure providers. I'll leave #126 open to allow facilitating a discussion, but there is not much more I can offer as this is not an issue with the network itself.

**Comment by Gelassen** [comment] 2022-10-26 03:08
Thank you for feedback. Does it mean you are as testnet
developers/stakeholders did not release any updates the goerly testnet
during the past ten days? Does it mean due decentralized nature of the
technology there's no way to communicate with infrastructure providers aka
nodes regarding this or similar issue? (actually there is should be one,
otherwise there wouldn't be a way to do such updates like the recent 'the
merge')
